# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kvcache.v1 import kvcache_pb2 as kvcache_dot_v1_dot_kvcache__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvcache/v1/kvcache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVCacheStub:
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/kvcache.v1.KVCache/Lookup',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_stream(
                '/kvcache.v1.KVCache/Fetch',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.KVChunk.FromString,
                _registered_method=True)
        self.BatchFetch = channel.unary_stream(
                '/kvcache.v1.KVCache/BatchFetch',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.BatchFetchRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.BatchKVChunk.FromString,
                _registered_method=True)
        self.Write = channel.stream_unary(
                '/kvcache.v1.KVCache/Write',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Replicate = channel.stream_unary(
                '/kvcache.v1.KVCache/Replicate',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Evict = channel.unary_unary(
                '/kvcache.v1.KVCache/Evict',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kvcache.v1.KVCache/Health',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.FromString,
                _registered_method=True)


class KVCacheServicer:
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    def Lookup(self, request, context):
        """Lookup reports per-block presence (metadata only, NO tensor bytes). Phase 1
        sends one block hash; block_hashes is repeated so longest-prefix lookups are a
        non-breaking extension. The CLIENT assembles the longest contiguous run of
        present blocks starting at index 0 (ADR 0011).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Fetch server-streams one block's KV tensor bytes in bounded chunks (ADR 0012).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchFetch(self, request, context):
        """BatchFetch server-streams MANY blocks' KV bytes over ONE call, so a multi-block
        prefix load pays a single round-trip instead of one per block (the load path is
        latency-bound on the per-block RTT, not bandwidth — Phase 4.5 finding). The request
        lists blocks in load order; every response frame carries the block's `index` so the
        client demuxes. The server streams blocks in order (no interleave), but the index
        makes the client robust regardless. A missing/mismatched block is reported with a
        single terminal frame (found=false, last=true, no data) so one absent block never
        fails the whole batch — the client just recomputes that block (ADR 0013/0016).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """Write client-streams one block. The FIRST message MUST be a WriteHeader; the
        rest are KVChunk data frames (ADR 0012). The receiving shard is the PRIMARY for
        this block (the ring owner); it assigns the version and asynchronously forwards
        the block to its replica via Replicate (Phase 3 Sub-stage B, ADR 0021).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request_iterator, context):
        """Replicate is the PRIMARY->REPLICA copy path (Sub-stage B). Same wire shape as
        Write (a WriteHeader then KVChunk frames), with two differences in meaning:
        - The header's `version` field is AUTHORITATIVE: the replica stores the block
        under the primary's assigned version, it does NOT mint its own (so primary
        and replica versions never diverge).
        - The replica stores locally and MUST NOT re-forward — this is what prevents a
        replication loop (each node forwarding to its own replica forever).
        Cache data is eventually consistent (ADR 0013), so this is fire-and-forget from
        the primary's side: the client was already acked before this ran.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evict(self, request, context):
        """Evict removes a block from the cache.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is a liveness/readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVCacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_stream_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.KVChunk.SerializeToString,
            ),
            'BatchFetch': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchFetch,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.BatchFetchRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.BatchKVChunk.SerializeToString,
            ),
            'Write': grpc.stream_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.SerializeToString,
            ),
            'Replicate': grpc.stream_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.SerializeToString,
            ),
            'Evict': grpc.unary_unary_rpc_method_handler(
                    servicer.Evict,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.v1.KVCache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.v1.KVCache', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVCache:
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Lookup',
            kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kvcache.v1.KVCache/Fetch',
            kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.KVChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchFetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kvcache.v1.KVCache/BatchFetch',
            kvcache_dot_v1_dot_kvcache__pb2.BatchFetchRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.BatchKVChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kvcache.v1.KVCache/Write',
            kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kvcache.v1.KVCache/Replicate',
            kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Evict',
            kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Health',
            kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
