# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kvcache.v1 import kvcache_pb2 as kvcache_dot_v1_dot_kvcache__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvcache/v1/kvcache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVCacheStub(object):
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/kvcache.v1.KVCache/Lookup',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_stream(
                '/kvcache.v1.KVCache/Fetch',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.KVChunk.FromString,
                _registered_method=True)
        self.Write = channel.stream_unary(
                '/kvcache.v1.KVCache/Write',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Evict = channel.unary_unary(
                '/kvcache.v1.KVCache/Evict',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kvcache.v1.KVCache/Health',
                request_serializer=kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.SerializeToString,
                response_deserializer=kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.FromString,
                _registered_method=True)


class KVCacheServicer(object):
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    def Lookup(self, request, context):
        """Lookup reports per-block presence (metadata only, NO tensor bytes). Phase 1
        sends one block hash; block_hashes is repeated so longest-prefix lookups are a
        non-breaking extension. The CLIENT assembles the longest contiguous run of
        present blocks starting at index 0 (ADR 0011).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Fetch server-streams one block's KV tensor bytes in bounded chunks (ADR 0012).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """Write client-streams one block. The FIRST message MUST be a WriteHeader; the
        rest are KVChunk data frames (ADR 0012).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evict(self, request, context):
        """Evict removes a block from the cache.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is a liveness/readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVCacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_stream_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.KVChunk.SerializeToString,
            ),
            'Write': grpc.stream_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.SerializeToString,
            ),
            'Evict': grpc.unary_unary_rpc_method_handler(
                    servicer.Evict,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.FromString,
                    response_serializer=kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.v1.KVCache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.v1.KVCache', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVCache(object):
    """KVCache stores serialized attention KV tensors keyed by an opaque 32-byte block
    hash. The hash is computed client-side (chained SHA-256 over token IDs, ADR 0011);
    the server treats it as opaque (ADR 0010). See docs/01-architecture.md.
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Lookup',
            kvcache_dot_v1_dot_kvcache__pb2.LookupRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kvcache.v1.KVCache/Fetch',
            kvcache_dot_v1_dot_kvcache__pb2.FetchRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.KVChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kvcache.v1.KVCache/Write',
            kvcache_dot_v1_dot_kvcache__pb2.WriteChunk.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Evict',
            kvcache_dot_v1_dot_kvcache__pb2.EvictRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.EvictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v1.KVCache/Health',
            kvcache_dot_v1_dot_kvcache__pb2.HealthRequest.SerializeToString,
            kvcache_dot_v1_dot_kvcache__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
